const stringDict=dict([
["build_defence_format","建造[BUILD]会增加[DEFENCE]城堡防御力，确定建造？（防御力数据可以点击城堡查看）"],
["mana", "魔法值"],
["money","银币"],["caesars","凯撒币"],["food","粮食"],["labor","空闲人口"],["person","人口"],["personmax","人口上限"],["stone","石头"],["wood","木材"],["caesar","凯撒"],
["coin", "银币"], ["freePeople", "空闲人口"], 
["share","分享"],["back","返回"],["change","修改"],["ok","确定"],["send","发送"],["cancel","取消"],["system","系统"],["devine","施展"],["retry","重试"],["help","帮忙"],["close","关闭"],["openbox","打开宝箱"],["askforhelp","求助好友"],
["attack","攻打"],["defence_power","防御力："],["emptyDefence", "未加成防御力"],["infpower","步兵战斗力"],["cavpower","骑兵战斗力"],["addsoldier","增兵"],["minussoldier","撤兵"],["getresource","运回资源"],["quick","加速"],["quickSendArmy", "增兵加速"],
["loading_str","正在载入，请稍候……"],["self","我"],
["request_done","该请求已处理"],
["friend_notload","抱歉，现在无法获得您的好友信息"],["friend_ally_notice","你可以访问好友和好友结盟，盟友会帮你战斗哦！"],["friend_invite","快来和我一起创造奇迹吧！"],["friend_invite_success","邀请成功！"],
["nest_style_cannotchange","宠物正在进化中，这个时候不可以更换哦！"],
["nest_talk_morning","早安，美好的一天又开启咯~"],["nest_talk_noon","午安，好饿呀，快点喂食吧~"],["nest_talk_night","晚安，早睡早起，睡觉啦~"],
["nest_talk_other","每次训练我都会更加强大，快训练我吧！"],["nest_talk_feedover","我已经吃饱啦，感谢前来喂养"],["nest_talk_notfeedover","快喂养我吧，我还可以继续被喂养哦~"],
["nest_talk_sleep","我还要适应成长，喂养到285点，我就可以飞翔咯！"],
["nest_getup_1","孵化成功啦！它是一条土属性龙。"],["nest_getup_2","成长为少年龙啦！"],
["nest_getup_format","[NAME][DESCRIBE]目前成长点为：[HEALTH]，属性为：[PROPERTY]，战斗力为：[ATTACK]"],
["nest_pet_name","请输入宠物名称："],["nest_pet_name_warning","命名之后不能更改，请慎重命名"],
["nest_gotohelp","为了更好地体验宠物系统，请查看帮助文档"],
["box_str_1","快帮我打开这个宝箱，"],["box_str_2","大家一起分享宝藏吧！"],["box_str_3","城堡里突然飘来一只<g>神秘宝箱<g>！！+快邀请好友一起开启吧！！+有神秘礼物等着你哦！"],
["god_bless_over","你已经施展过神迹了！"],
["share_format","[NAME][DESCRIBE]，赶快加入与[NAME]一起打造属于自己的奇迹帝国吧！"],
["share_box_format","[NAME]获得了一只神秘的宝箱，但是需要你们的帮助才能打开，快去帮助TA吧！"],
["share_petup_1","成功孵化出宠物"],["share_petup_2","的幼龙长大啦"],
["share_openbox","打开了一只神秘宝箱"],
["default_petname","我的宠物"],
["news_nonews","还没有任何消息哦！"],
["news_element0","<b>[NAME]<b>访问了你的领地"],
["news_element1","<b>[NAME]<b>帮助你打理城堡"],
["news_element2","<b>[NAME]<b>赠送了你礼物"],
["news_element3","你战胜了<b>[NAME]<b>"],
["news_element4","<b>[NAME]<b>战胜了你"],
["news_element5","<b>[NAME]<b>帮助你打开宝箱"],
["news_element6","<b>[NAME]<b>帮助你喂养了宠物"],
["gift_element0","[NAME]赠送你礼物[GIFT]"],
["gift_element1","[NAME]向你索取礼物[GIFT]"],
["monster_refresh_format","哈哈哈，[NAME]领主，献出你的粮食吧，否则你们将永不得安宁！"],
["monster_foodwilllost","下次登录之前还没有把怪兽消灭，怪兽会抢夺你的粮食哦！ 进入地图消灭它们吧！"],
["warrecord_notice_format","你的领地发生了[NUM]场战争，观看可以知道士兵损失详细情况，是否观看？"],
["war_newmap_notice","恭喜你进入了新的地图！提示：不要太快进入更高等级的地图哦，先暗中积攒兵力吧^_^"],
["spy_notice","注：侦察级别越高，获得的信息越多哦！"],["spy_unknown","未侦察到"],["spy_result_format","你损失了[NUM]个侦察兵，获取了[WHO]的情报："],
["spy_result2_noenemy","未发现有进攻这个城堡的军队"],["spy_result2_format","已有[NUM]支军队正在进攻这个城堡，最快抵达时间为[TIME]以后"],
["spy_result2_mode3_format","总计战斗力为[NUM]"],
["chat_empty","内容为空，无法发送！"],["chat_wordlimit","字数超过30个汉字，无法发送！"],["chat_nettimeout","超时了，你的消息发送失败"],
["text_wordlimit_format","限[NUM]个汉字！"],["text_cannotset","不能改成这个名字！"],["text_nettimeout","抱歉，因网络原因本次改名失败！"],
["text_message_send","请输入留言内容："],["text_empty","内容不能为空"],["text_chat_nettimeout","抱歉，发送失败，请重新发送^_^"],
["message_send_success","发送成功！"],["text_empire_name","请输入帝国名称："],
["update_normal","普通升级"],["update_caesars","快速升级"],["update_warning","该建筑正在运作，如果升级将会导致运作中断，确认升级？"],
["onekey_plant","一键播种"],["onekey_harvest","一键收获"],["onekey_product","一键收税"],["onekey_visit_normal","一键普通访问"],["onekey_visit_inc","一键累计访问"],["onekey_title","一键操作"],
["onekey_gotohelp","查看帮助及如何免费使用？"],
["tab_fighting","作战中"],["tab_attackable","可攻打"],["tab_fortress", "要塞"],
["nobattle_fail_whenhasattack","抱歉，正在进攻其他玩家时不能开启保护模式"],
["nobattle_whenattack","在保护期中攻打其他玩家，保护状态将会终止"],
["attack_whenattacked","你已经在进攻他了哦！"],["attack_whennobattle","该玩家的领地正在受保护中"],["attack_whenwon","你已经征服他了哦！"],["attack_whenupdated","抱歉，该玩家已经升级到更高等级的地图。"],
["attack_cancel","是否撤消本次进攻？你的战斗力将立即回到城堡。"],["attacktime","行军时间"],["attacktime_notice","*骑兵比重越大，行军时间越短"],
["state_attacking","进攻中"],["state_defencing","防御中"],["state_fighting","正在交战"],["state_adding","增兵中"],
["net_state_1","貌似断网了，请检查是否有网络连接"],["net_state_2","网络连接遇到了问题，请稍候再试"],
["master","领主："],[":","："],
["user_notoccupy","未征服"],["user_occupy","已征服"],["user_protected","保护中"],["user_fighting","正在交战"],["user_attacking","进攻中"],
["resource_get_format","该要塞每小时生产银币[MONEY]，粮食[FOOD]，木材[WOOD]，石头[STONE]，下一次生产结束倒计时：[TIME]"],
["goSee", "去看看"], ["IKnow", "知道了"], ["genAdd", "普通增加"], ["fastAdd", "快速增加"], ["chooseDefence", "你所选择要增加的防御里："], 
["youLeft", "你还剩[NUM]个盟友名额。"], ["sureToally", "你确定与Ta结盟吗？"],
["allyOk", "在你战斗时，盟军将会提供你士兵援助。请慎重结盟，取消结盟会消耗凯撒币的哦！"],
["makeAlly", "结盟"], ["cancelAlly", "确定取消与[NAME]的结盟？"],
["punish", "惩罚："], ["allyUp", "你的盟友数已经达到上限。"],
["add", "增加"], ["addAlly", "增加一个盟友位"], 
["sendSuc",  "请求发送成功！"],
["downloading", "正在下载相关文件..."],
["downMusic", "开启音乐需要下载800K左右音乐文件，是否下载？"],
["showDownNow", "为了更好的体验游戏，你需要下载3M左右的图片，建议使用wifi，是否下载？"],
["", ""],

]);



const staticString = [
"你需要升到6级才能开启战争模式",
"开启战争模式之后暂时就不能退出咯，请查看帮助文档",
"恭喜你抵挡住了[ENAME]的攻势，保卫了领地不被侵犯！",
"[ENAME]兵力过于强大，你的军队不幸战败，快去加强你的军事力量吧！",
"[ENAME]兵力过于强大，回去厉兵秣马，来日再战！",
"恭喜你战胜了[ENAME]，你离帝王宝座又近了一步！",
"如何提高战斗力",
"[USERNAME]进入新的地图啦，赶快加入与[USERNAME]一起打造属于自己的奇迹帝国吧！",
"[USERNAME]升级为[NOBNAME]啦，赶快加入与[USERNAME]一起打造属于自己的奇迹帝国吧！",
"[USERNAME]的领地升级啦，赶快加入与[USERNAME]一起打造属于自己的奇迹帝国吧！",
"[USERNAME]成功战胜侵略者，赶快加入与[USERNAME]一起打造属于自己的奇迹帝国吧！",
"[USERNAME]被YYYY[ENAME]打败了，赶快加入帮助[USERNAME]复仇吧！",
"[USERNAME]的大军被击退，赶快加入与[USERNAME]一起侵略其他领地吧！",
"[USERNAME]战胜了[ENAME]，赶快加入与[USERNAME]一起打造属于自己的奇迹帝国吧！",
"你需要升到15级才能使用一键操作",
"你没有空闲的农田，不能使用一键操作",
"你的农作物正在生长，无法一键收获",
"[WHO]的[TYPE]数需要达到[NUM]才能升到下一等级。该卡每升一级将会增加1点魔法上限！",
"[WHO]还需要战胜[NUM]个用户才能升级到[CARD]，该卡每升级一级将会增加一点魔法值上限。",
"你的店铺正在工作，无法一键收税",
"恭喜你获得了该紫金卡片，你的魔法值上限增加了两点",
"恭喜，嫦娥卡升到紫金级别，魔法值上限增加了1",
"把丰收之神升到紫金级别，该卡每升一级将会增加一点魔法值上限。",
"把财富之神升到紫金级别，该卡每升一级将会增加一点魔法值上限。",
"抱歉，你已经访问过所有好友了！",
"每天宠物前100次训练才会增加1点战斗力哦！",
"你一键访问了[NUM]个好友，获得了[MONEY]银币奖励",
"升级友谊之神到紫金级别",
"还差[NUM]个好友",
"还需要帮助好友打开[NUM]个宝箱",
"还需要帮助好友喂养[NUM]次宠物",
"需要升到[NUM]级",
"你现在可以永久免费使用一键普通访问好友功能咯！",
"[NAME]晒出了自己领地的截图，大家快来围观吧！",
"",
"http://getmugua.com",
"每天自己只能喂养一次，好友可以帮忙继续喂养。假如当天自己或好友都没喂养，成长点会下降哦！",
"该宠物蛋即将孵化，等孵化之后才能继续喂养，感谢帮忙^_^",
"每天你只能帮同一个好友喂养一次^_^",
"[NAME]的宠物已经有[NUM]个好友喂养过了，谢谢帮忙^_^"];

const DownWarPic = 0;
const DownPetPic = 1;
const DownAllPic = 2;
const DownWarn = -2000;
const DownAniPic = 3;
const DownMusic = 4;
const ShowDownYet = -10000;

const NotDownload = -1;
const UseCata = -3000;
const AttWithCata = 100;
const AttNoCata = 101;
const NoCata = -3001;

const Tasks = 
[
dict([["req", "build"],["des", ["开垦农田","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","开垦普通农田"]],["checknum", 1],["lev", 3],["pair", ["ground_id", 1]],["reward", [200, 5, 0]],["type", 0],["id", 0]]),
dict([["req", "planting"],["des", ["种植小麦","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植小麦","提示：先点击空闲农田，再点击播种图标，选择小麦"]],["checknum", 3],["lev", 3],["pair", ["object_id", 0, "type", 0]],["reward", [300, 15, 0]],["type", 0],["id", 1]]),
dict([["req", "money"],["des", ["面包房收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","面包房收税"]],["checknum", 100],["lev", 3],["pair", ["bid", 0]],["reward", [200, 15, 0]],["type", 1],["id", 2]]),
dict([["req", "dialog-castleinfo"],["des", ["查看经营信息","点击城堡可以查看到许多信息。同时也进行城堡升级、增加城堡防御力","查看经营信息","提示：点击城堡查看经营页面信息"]],["checknum", 1],["lev", 3],["reward", [100, 5, 0]],["type", 2],["id", 3]]),
dict([["req", "dialog-help"],["des", ["查看帮助文档","帮助文档有详细的关于游戏的一些设置资料，可以帮助大家更好地畅游游戏","查看帮助文档","提示：先点击menu键（或下菜单设置按钮），再点击帮助选项"]],["checknum", 1],["lev", 3],["reward", [100, 5, 0]],["type", 2],["id", 4]]),
dict([["req", "soldiers"],["des", ["训练民兵","训练士兵可以攻打其他玩家、攻击怪兽、探险...","训练民兵","提示：先点击空闲的步兵训练营，再选择民兵选项"]],["checknum", 30],["lev", 4],["pair", ["btype", 0, "objtype", 0]],["reward", [500, 20, 0]],["type", 1],["id", 5]]),
dict([["req", "defeatmonster"],["des", ["消灭怪物","消灭怪兽会获得特殊物品等奖励，还能激活怪兽荣誉卡片哦！","消灭怪物","提示：先点击地图图标，再选择怪兽攻打"]],["checknum", 1],["lev", 4],["pair", []],["reward", [500, 20, 0]],["type", 0],["id", 6]]),
dict([["req", "expand"],["des", ["扩地","扩地之后可以建造更多的建筑！","扩地","提示：点击建造按钮，进入建造大对话框，再点击最右边的扩地按钮，选择扩地的方式"]],["checknum", 1],["lev", 4],["pair", []],["reward", [600, 20, 0]],["type", 0],["id", 7]]),
dict([["req", "getfriend"],["des", ["访问凯撒的领地","参观凯撒的领地，也许你会有意想不到的收获哦！","访问凯撒的领地","提示：先点击好友列表，再点击凯撒图像"]],["checknum", 1],["lev", 5],["pair", ["otherid", 0]],["reward", [150, 5, 0]],["type", 0],["id", 8]]),
dict([["req", "dialog-circle"],["des", ["加好友","进入圈子可以加好友、反馈bug、查看游戏最新更新信息！","去圈子加好友","提示：先点击好友列表，再点击圈子图标，点击\"成为粉丝\"，再次点击该按钮，点击查看所有粉丝添加好友"]],["checknum", 1],["lev", 5],["reward", [700, 10, 0]],["type", 2],["id", 9]]),
dict([["req", "selectgift"],["des", ["赠送好友礼物","你可以免费赠送好友一个特殊物品！","赠送好友礼物","提示：前往好友页面，点击左侧礼物图标，选择一个礼物赠送给好友"]],["checknum", 1],["lev", 5],["pair", ["askorgive", 0]],["reward", [200, 10]],["type", 0],["id", 10]]),
dict([["req", "selectgift"],["des", ["向好友索要礼物","向好友索要礼物，好友可以免费赠送你特殊物品","向好友索要礼物","提示：前往好友页面，点击右侧礼物图标，选择一个礼物向好友索要"]],["checknum", 1],["lev", 5],["pair", ["askorgive", 1]],["reward", [300, 10, 0]],["type", 0],["id", 11]]),
dict([["req", "completeopen"],["des", ["打开宝箱","好友能帮你打开神秘宝箱哦！请求他们帮你打开吧，。","打开宝箱","提示：左侧有一个宝箱，点击宝箱，可以使用凯撒币完成，也可以请求好友帮忙"]],["checknum", 1],["lev", 5],["pair", []],["reward", [500, 20, 0]],["type", 0],["id", 12]]),
dict([["des", ["打分","如果你喜欢奇迹帝国，去安卓市场打个五分吧，谢谢^_^","前往Androidmarket打分"]],["checknum", 1],["lev", 5],["reward", [-10, 30, 0]],["type", 3],["id", 13]]),
dict([["req", "updatebuilding"],["des", ["升级农舍","高级建筑会大大加快领地的发展！","升级普通农舍","提示：先点击农舍，再点击升级图标"]],["checknum", 1],["lev", 6],["pair", ["ground_id", 101]],["reward", [500, 20, 0]],["type", 0],["id", 14]]),
dict([["req", "person"],["des", ["招募人口","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","招募人口","提示：先点击空闲民居，再点击招募图标"]],["checknum", 50],["lev", 6],["pair", []],["reward", [500, 30, 0]],["type", 1],["id", 15]]),
dict([["req", "build"],["des", ["建造民宅","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","建造普通民宅"]],["checknum", 2],["lev", 6],["pair", ["ground_id", 112]],["reward", [400, 25, 0]],["type", 0],["id", 16]]),
dict([["req", "planting"],["des", ["种植胡萝卜","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植胡萝卜"]],["checknum", 6],["lev", 6],["pair", ["object_id", 1, "type", 0]],["reward", [600, 30, 0]],["type", 0],["id", 17]]),
dict([["req", "money"],["des", ["肉铺收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","普通肉铺收税"]],["checknum", 1500],["lev", 6],["pair", ["bid", 6]],["reward", [800, 80, 1]],["type", 1],["id", 18]]),
dict([["req", "helpopen"],["des", ["帮助好友打开宝箱","帮助好友打开宝箱你会获得丰厚的回报","帮助好友打开宝箱","提示：前往好友页面，点击宝箱图标，点击帮助"]],["checknum", 5],["lev", 7],["pair", []],["reward", [1000, 25, 0]],["type", 0],["id", 25]]),
dict([["des", ["邀请好友","访问好友有银币奖励，多加些好友吧！","邀请好友","提示：先点击好友列表，邀请还不是游戏用户的木瓜好友，也可以点击最后面的问号图标邀请好友"]],["checknum", 3],["lev", 7],["reward", [2000, 50, 1]],["type", 4],["id", 26]]),
dict([["req", "planting"],["des", ["种植玉米","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植玉米"]],["checknum", 4],["lev", 8],["pair", ["object_id", 2, "type", 0]],["reward", [1200, 48, 1]],["type", 0],["id", 27]]),
dict([["req", "build"],["des", ["召唤丰收之神","神像可以施展魔法，部分神像升到顶级之后可以一键操作","召唤丰收之神","提示：先点击丰收之神，再点击神迹图标施展神迹"]],["checknum", 1],["lev", 8],["pair", ["ground_id", 400]],["reward", [1000, 40, 0]],["type", 0],["id", 28]]),
dict([["req", "godbless"],["des", ["施展神迹","施展神迹可以大幅度增加相关建筑的产值！"]],["checknum", 1],["lev", 8],["pair", ["godtype", 0]],["reward", [1000, 30, 1]],["type", 0],["id", 29]]),
dict([["req", "planting"],["des", ["种植菠萝","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植菠萝"]],["checknum", 6],["lev", 8],["pair", ["object_id", 3, "type", 0]],["reward", [1200, 36, 0]],["type", 0],["id", 30]]),
dict([["req", "build"],["des", ["建造神奇屋","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","建造普通神奇屋"]],["checknum", 1],["lev", 8],["pair", ["ground_id", 160]],["reward", [1000, 50, 1]],["type", 0],["id", 31]]),
dict([["des", ["晒图","让大家欣赏欣赏你的领地吧！","截图并分享","提示：先点击menu键（或下菜单设置按钮），再点击截图"]],["checknum", 1],["lev", 8],["reward", [800, 30, 0]],["type", 5],["id", 32]]),
dict([["des", ["帮助好友","帮助好友清除负面状态会有奖励哦！","帮助好友清除负面状态","提示：前往好友页面，帮助好友农田除虫、除草或是帮助好友建筑维修、打扫"]],["checknum", 1],["lev", 9],["reward", [1200, 40, 0]],["type", 6],["id", 35]]),
dict([["req", "updatebuilding"],["des", ["升级面包房","高级建筑会大大加快领地的发展！","升级普通面包房"]],["checknum", 1],["lev", 9],["pair", ["ground_id", 301]],["reward", [1000, 40, 0]],["type", 0],["id", 36]]),
dict([["req", "money"],["des", ["中级面包房收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","中级面包房收税"]],["checknum", 700],["lev", 9],["pair", ["bid", 1]],["reward", [1500, 60, 0]],["type", 1],["id", 37]]),
dict([["req", "build"],["des", ["开垦水晶农田","特殊农田可以大大提高产量！","开垦水晶农田"]],["checknum", 2],["lev", 10],["pair", ["ground_id", 2]],["reward", [2000, 100, 1]],["type", 0],["id", 38]]),
dict([["req", "build"],["des", ["建造伐木场","木材和石材用户建筑升级，投石车等物品的建造","建造普通锯木厂"]],["checknum", 1],["lev", 10],["pair", ["ground_id", 5]],["reward", [1500, 50, 0]],["type", 0],["id", 39]]),
dict([["req", "wood"],["des", ["采集枫树","木材和石材用户建筑升级，投石车等物品的建造","采集枫树木材"]],["checknum", 30],["lev", 10],["pair", ["objid", 0]],["reward", [1500, 60, 0]],["type", 1],["id", 40]]),
dict([["des", ["邀请好友","访问好友有银币奖励，多加些好友吧！","邀请好友","提示：进入好友列表，向有邀请提示的好友进行邀请"]],["checknum", 5],["lev", 10],["reward", [3000, 70, 1]],["type", 4],["id", 41]]),
dict([["req", "completepay"],["des", ["充值送礼","现在充值将会赠送凯撒币啦，还等什么？","充值送礼"]],["checknum", 1],["lev", 10],["pair", []],["reward", [1000, 200, 1]],["type", 0],["id", 42]]),
dict([["req", "build"],["des", ["建造砖石路","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造砖石路"]],["checknum", 6],["lev", 11],["pair", ["ground_id", 500]],["reward", [600, 30, 0]],["type", 0],["id", 43]]),
dict([["req", "build"],["des", ["建造花坛","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造花坛"]],["checknum", 6],["lev", 11],["pair", ["ground_id", 505]],["reward", [600, 60, 0]],["type", 0],["id", 44]]),
dict([["req", "build"],["des", ["建造黄金路","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造黄金路"]],["checknum", 3],["lev", 11],["pair", ["ground_id", 504]],["reward", [1800, 50, 1]],["type", 0],["id", 45]]),
dict([["req", "build"],["des", ["建造别墅","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","建造别墅"]],["checknum", 2],["lev", 11],["pair", ["ground_id", 124]],["reward", [1200, 30, 0]],["type", 0],["id", 46]]),
dict([["req", "build"],["des", ["建造精灵灯","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造精灵灯"]],["checknum", 1],["lev", 11],["pair", ["ground_id", 512]],["reward", [1200, 30, 1]],["type", 0],["id", 47]]),
dict([["req", "build"],["des", ["建造魔法水井","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造魔法水井"]],["checknum", 1],["lev", 11],["pair", ["ground_id", 520]],["reward", [1200, 90, 1]],["type", 0],["id", 48]]),
dict([["req", "planting"],["des", ["种植茄子","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植茄子"]],["checknum", 6],["lev", 11],["pair", ["object_id", 4, "type", 0]],["reward", [1300, 100, 0]],["type", 0],["id", 49]]),
dict([["req", "planting"],["des", ["种植西红柿","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植西红柿"]],["checknum", 6],["lev", 11],["pair", ["object_id", 5, "type", 0]],["reward", [1300, 50, 1]],["type", 0],["id", 50]]),
dict([["req", "build"],["des", ["召唤人口之神","神像可以施展魔法，部分神像升到顶级之后可以一键操作","召唤人口之神"]],["checknum", 1],["lev", 12],["pair", ["ground_id", 401]],["reward", [1500, 50, 0]],["type", 0],["id", 51]]),
dict([["req", "godbless"],["des", ["施展神迹","神迹大大可以提高相关建筑产量！","人口之神施展神迹"]],["checknum", 1],["lev", 12],["pair", ["godtype", 1]],["reward", [1100, 50, 1]],["type", 0],["id", 52]]),
dict([["req", "person"],["des", ["招募人口","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","招募人口"]],["checknum", 100],["lev", 12],["pair", []],["reward", [1500, 100, 0]],["type", 1],["id", 53]]),
dict([["req", "money"],["des", ["餐厅收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通餐厅收税"]],["checknum", 3000],["lev", 12],["pair", ["bid", 9]],["reward", [1500, 70, 0]],["type", 1],["id", 54]]),
dict([["req", "build"],["des", ["建造骑兵训练营","落后就要挨打，建造士兵训练营来训练士兵吧！","建造普通骑兵训练营"]],["checknum", 1],["lev", 13],["pair", ["ground_id", 203]],["reward", [1800, 40, 0]],["type", 0],["id", 56]]),
dict([["req", "soldiers"],["des", ["训练骑兵","训练士兵可以攻打其他玩家、攻击怪兽、探险...","训练轻骑兵"]],["checknum", 40],["lev", 13],["pair", ["btype", 1, "objtype", 0]],["reward", [2000, 50, 0]],["type", 1],["id", 57]]),
dict([["req", "planting"],["des", ["种植青椒","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植青椒"]],["checknum", 6],["lev", 13],["pair", ["object_id", 6, "type", 0]],["reward", [1800, 30, 0]],["type", 0],["id", 59]]),
dict([["req", "godbless"],["des", ["施展神迹","施展神迹可以大幅度增加相关建筑的产值！"]],["checknum", 1],["lev", 13],["pair", ["godtype", 0]],["reward", [1200, 50, 1]],["type", 0],["id", 60]]),
dict([["req", "updatebuilding"],["des", ["升级步兵训练营","高级建筑会大大加快领地的发展！","升级普通步兵训练营"]],["checknum", 1],["lev", 14],["pair", ["ground_id", 201]],["reward", [1800, 80, 0]],["type", 0],["id", 62]]),
dict([["req", "soldiers"],["des", ["训练步兵","训练士兵可以攻打其他玩家、攻击怪兽、探险...","训练步兵","提示：先点击中级步兵训练营，再选择步兵图标"]],["checknum", 60],["lev", 14],["pair", ["btype", 0, "objtype", 1]],["reward", [3000, 90, 0]],["type", 1],["id", 63]]),
dict([["req", "money"],["des", ["书店收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通书店收税"]],["checknum", 6000],["lev", 14],["pair", ["bid", 15]],["reward", [1800, 150, 1]],["type", 1],["id", 65]]),
dict([["req", "updatebuilding"],["des", ["升级神奇屋","高级建筑会大大加快领地的发展！","升级神奇屋"]],["checknum", 1],["lev", 14],["pair", ["ground_id", 161]],["reward", [2000, 200, 1]],["type", 0],["id", 66]]),
dict([["req", "build"],["des", ["建造豪宅","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","建造豪宅"]],["checknum", 1],["lev", 15],["pair", ["ground_id", 136]],["reward", [1500, 60, 0]],["type", 0],["id", 67]]),
dict([["req", "build"],["des", ["建造普通水井","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造普通水井"]],["checknum", 1],["lev", 15],["pair", ["ground_id", 519]],["reward", [300, 15, 0]],["type", 0],["id", 68]]),
dict([["req", "wood"],["des", ["采集柳树","木材和石材用户建筑升级，投石车等物品的建造","采集柳树木材"]],["checknum", 130],["lev", 15],["pair", ["objid", 1]],["reward", [2100, 180, 0]],["type", 1],["id", 69]]),
dict([["req", "money"],["des", ["诊所收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通诊所收税"]],["checknum", 5000],["lev", 15],["pair", ["bid", 12]],["reward", [1500, 100, 0]],["type", 1],["id", 70]]),
dict([["req", "money"],["des", ["中级肉铺收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从中级肉铺收税"]],["checknum", 3500],["lev", 15],["pair", ["bid", 7]],["reward", [2500, 250, 1]],["type", 1],["id", 71]]),
dict([["req", "planting"],["des", ["种植南瓜","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植南瓜"]],["checknum", 6],["lev", 16],["pair", ["object_id", 7, "type", 0]],["reward", [1800, 96, 0]],["type", 0],["id", 72]]),
dict([["req", "build"],["des", ["召唤战争之神","神像可以施展魔法，部分神像升到顶级之后可以一键操作","召唤战争之神"]],["checknum", 1],["lev", 16],["pair", ["ground_id", 403]],["reward", [1600, 100, 0]],["type", 0],["id", 73]]),
dict([["req", "godbless"],["des", ["施展神迹","神迹大大可以提高相关建筑产量！","战争之神施展神迹"]],["checknum", 1],["lev", 16],["pair", ["godtype", 3]],["reward", [1300, 100, 1]],["type", 0],["id", 74]]),
dict([["req", "updatebuilding"],["des", ["升级神像","把神像升到更高级将会有更强的魔法效果！","升级任意一个神像"]],["checknum", 1],["lev", 16],["pair", ["ground_id", 404]],["reward", [4000, 250, 1]],["type", 0],["id", 75]]),
dict([["req", "build"],["des", ["建造花丛","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造花丛"]],["checknum", 3],["lev", 17],["pair", ["ground_id", 521]],["reward", [900, 45, 0]],["type", 0],["id", 76]]),
dict([["req", "build"],["des", ["建造樱花树","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造樱花树"]],["checknum", 3],["lev", 17],["pair", ["ground_id", 528]],["reward", [2100, 100, 1]],["type", 0],["id", 77]]),
dict([["req", "wood"],["des", ["采集白杨树","木材和石材用户建筑升级，投石车等物品的建造","采集白杨树木材"]],["checknum", 200],["lev", 17],["pair", ["objid", 2]],["reward", [4000, 300, 1]],["type", 1],["id", 78]]),
dict([["req", "updatebuilding"],["des", ["升级豪宅","高级建筑会大大加快领地的发展！","升级豪宅到最高级"]],["checknum", 1],["lev", 17],["pair", ["ground_id", 138]],["reward", [2500, 98, 0]],["type", 0],["id", 79]]),
dict([["des", ["邀请好友","访问好友有银币奖励，多加些好友吧！","邀请好友","提示：进入好友列表，向有邀请提示的好友进行邀请"]],["checknum", 3],["lev", 17],["reward", [5500, 155, 1]],["type", 4],["id", 80]]),
dict([["req", "build"],["des", ["建造采石厂","木材和石材用户建筑升级，投石车等物品的建造","建造普通采石厂"]],["checknum", 1],["lev", 18],["pair", ["ground_id", 6]],["reward", [2100, 56, 0]],["type", 0],["id", 81]]),
dict([["req", "stone"],["des", ["采集砾石","木材和石材用户建筑升级，投石车等物品的建造","采集砾石"]],["checknum", 50],["lev", 18],["pair", ["objid", 0]],["reward", [2400, 120, 0]],["type", 1],["id", 82]]),
dict([["req", "updatebuilding"],["des", ["升级步兵训练营","高级建筑会大大加快领地的发展！","升级中级步兵训练营"]],["checknum", 1],["lev", 18],["pair", ["ground_id", 202]],["reward", [3000, 150, 0]],["type", 0],["id", 83]]),
dict([["req", "build"],["des", ["建造忘忧草","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造忘忧草"]],["checknum", 4],["lev", 19],["pair", ["ground_id", 524]],["reward", [1200, 80, 0]],["type", 0],["id", 85]]),
dict([["req", "build"],["des", ["建造灌木","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造灌木"]],["checknum", 3],["lev", 19],["pair", ["ground_id", 532]],["reward", [900, 60, 0]],["type", 0],["id", 86]]),
dict([["req", "build"],["des", ["建造天使雕像","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造天使雕像"]],["checknum", 1],["lev", 19],["pair", ["ground_id", 538]],["reward", [2000, 100, 1]],["type", 0],["id", 87]]),
dict([["req", "updatebuilding"],["des", ["升级诊所","高级建筑会大大加快领地的发展！","升级普通诊所"]],["checknum", 1],["lev", 19],["pair", ["ground_id", 313]],["reward", [3000, 100, 0]],["type", 0],["id", 88]]),
dict([["req", "build"],["des", ["开垦宝石农田","特殊农田可以大大增加粮食产量！","开垦宝石农田"]],["checknum", 4],["lev", 20],["pair", ["ground_id", 3]],["reward", [4000, 200, 1]],["type", 0],["id", 89]]),
dict([["req", "planting"],["des", ["种植桃树","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植桃树"]],["checknum", 3],["lev", 20],["pair", ["object_id", 8, "type", 0]],["reward", [3000, 150, 1]],["type", 0],["id", 90]]),
dict([["req", "build"],["des", ["建造庄园","民居可以招募人口，人口可以用来建造建筑、训练成士兵！","建造普通庄园"]],["checknum", 2],["lev", 20],["pair", ["ground_id", 148]],["reward", [2100, 100, 0]],["type", 0],["id", 91]]),
dict([["req", "build"],["des", ["召唤财富之神","神像可以施展魔法，部分神像升到顶级之后可以一键操作","召唤财富之神"]],["checknum", 1],["lev", 20],["pair", ["ground_id", 402]],["reward", [2300, 130, 0]],["type", 0],["id", 92]]),
dict([["req", "godbless"],["des", ["施展神迹","神迹大大可以提高相关建筑产量！","施展神迹"]],["checknum", 1],["lev", 20],["pair", ["godtype", 2]],["reward", [1400, 100, 1]],["type", 0],["id", 93]]),
dict([["req", "money"],["des", ["服装店收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通服装店收税"]],["checknum", 3500],["lev", 21],["pair", ["bid", 18]],["reward", [2600, 150, 0]],["type", 1],["id", 94]]),
dict([["req", "wood"],["des", ["采集梧桐","木材和石材用户建筑升级，投石车等物品的建造","采集梧桐木材"]],["checknum", 100],["lev", 21],["pair", ["objid", 3]],["reward", [2700, 180, 0]],["type", 1],["id", 95]]),
dict([["req", "expand"],["des", ["扩地","有更多的地，才有更多的房！","扩地"]],["checknum", 1],["lev", 21],["pair", []],["reward", [3000, 300, 0]],["type", 0],["id", 96]]),
dict([["req", "money"],["des", ["高级肉铺收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从高级肉铺收税"]],["checknum", 6000],["lev", 21],["pair", ["bid", 8]],["reward", [4000, 300, 1]],["type", 1],["id", 97]]),
dict([["req", "stone"],["des", ["采集玄武石","木材和石材用户建筑升级，投石车等物品的建造","采集玄武石"]],["checknum", 130],["lev", 22],["pair", ["objid", 1]],["reward", [2800, 210, 0]],["type", 1],["id", 98]]),
dict([["req", "money"],["des", ["中级书店收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从中级书店收税"]],["checknum", 10000],["lev", 22],["pair", ["bid", 16]],["reward", [4000, 280, 1]],["type", 1],["id", 99]]),
dict([["req", "planting"],["des", ["种植西瓜","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植西瓜"]],["checknum", 6],["lev", 23],["pair", ["object_id", 9, "type", 0]],["reward", [2900, 240, 0]],["type", 0],["id", 101]]),
dict([["req", "money"],["des", ["赌场收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通赌场收税"]],["checknum", 13000],["lev", 24],["pair", ["bid", 24]],["reward", [4500, 350, 1]],["type", 1],["id", 103]]),
dict([["req", "stone"],["des", ["采集石灰岩","木材和石材用户建筑升级，投石车等物品的建造","采集石灰岩"]],["checknum", 200],["lev", 24],["pair", ["objid", 2]],["reward", [4500, 350, 1]],["type", 1],["id", 104]]),
dict([["req", "build"],["des", ["建造枫树","装饰可以增加人口上限，部分装饰还可以增加魔法值上限！","建造枫树"]],["checknum", 3],["lev", 25],["pair", ["ground_id", 535]],["reward", [1400, 90, 1]],["type", 0],["id", 106]]),
dict([["req", "planting"],["des", ["种植草莓","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植草莓"]],["checknum", 6],["lev", 25],["pair", ["object_id", 11, "type", 0]],["reward", [5400, 420, 1]],["type", 0],["id", 107]]),
dict([["req", "wood"],["des", ["采集橡树","木材和石材用户建筑升级，投石车等物品的建造","采集橡树木材"]],["checknum", 300],["lev", 25],["pair", ["objid", 5]],["reward", [5700, 420, 0]],["type", 1],["id", 108]]),
dict([["req", "planting"],["des", ["种植芒果","粮食很重要，凯撒农作物、特殊农田、丰收女神都可以大幅度提高粮食产量！","种植芒果"]],["checknum", 6],["lev", 26],["pair", ["object_id", 10, "type", 0]],["reward", [3300, 240, 1]],["type", 0],["id", 110]]),
dict([["req", "updatebuilding"],["des", ["升级神像","把神像升到更高级将会有更强的魔法效果！","升级任一白银神像"]],["checknum", 1],["lev", 26],["pair", ["ground_id", 408]],["reward", [4000, 450, 1]],["type", 0],["id", 111]]),
dict([["req", "updatebuilding"],["des", ["升级神奇屋","高级建筑会大大加快领地的发展！","升级中级神奇屋"]],["checknum", 1],["lev", 26],["pair", ["ground_id", 162]],["reward", [5000, 450, 0]],["type", 0],["id", 112]]),
dict([["req", "stone"],["des", ["采集花岗岩","木材和石材用户建筑升级，投石车等物品的建造","采集花岗岩"]],["checknum", 100],["lev", 27],["pair", ["objid", 3]],["reward", [3000, 300, 0]],["type", 1],["id", 113]]),
dict([["req", "updatebuilding"],["des", ["升级骑兵训练营","高级建筑会大大加快领地的发展！","升级中级骑兵训练营"]],["checknum", 1],["lev", 27],["pair", ["ground_id", 205]],["reward", [4000, 480, 1]],["type", 0],["id", 114]]),
dict([["req", "planting"],["des", ["种植玉米","听小新说，这个农田能种出水晶玉米哦！！","在水晶农田上种植玉米"]],["checknum", 6],["lev", 27],["pair", ["object_id", 2, "type", 0, "bid", 2]],["reward", [4500, 500, 1]],["type", 0],["id", 115]]),
dict([["req", "wood"],["des", ["采集松树","木材和石材用户建筑升级，投石车等物品的建造","采集松树木材"]],["checknum", 200],["lev", 28],["pair", ["objid", 4]],["reward", [4200, 300, 0]],["type", 1],["id", 116]]),
dict([["req", "money"],["des", ["中级赌场收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从中级赌场收税"]],["checknum", 16000],["lev", 28],["pair", ["bid", 25]],["reward", [5600, 480, 0]],["type", 1],["id", 117]]),
dict([["req", "money"],["des", ["高级书店收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从高级书店收税"]],["checknum", 15000],["lev", 28],["pair", ["bid", 17]],["reward", [5600, 480, 1]],["type", 1],["id", 118]]),
dict([["req", "money"],["des", ["首饰店收税","银币是不可或缺的资源，高级店铺可以收集更多的银币！","从普通首饰店收税"]],["checknum", 7000],["lev", 29],["pair", ["bid", 21]],["reward", [4200, 300, 0]],["type", 1],["id", 119]]),
dict([["req", "planting"],["des", ["种植草莓","听小新说，这个农田能种出神奇草莓哦！！","在宝石农田上种植草莓"]],["checknum", 6],["lev", 29],["pair", ["object_id", 11, "type", 0, "bid", 3]],["reward", [6000, 500, 1]],["type", 0],["id", 120]]),
dict([["req", "money"],["des", ["高级赌场收税","高级建筑的性价比更高！","从高级赌场收税"]],["checknum", 22000],["lev", 29],["pair", ["bid", 26]],["reward", [6000, 500, 1]],["type", 1],["id", 121]]),
dict([["req", "build"],["des", ["开垦精灵农田","特殊农田可以大大增加粮食产量！","开垦精灵农田"]],["checknum", 4],["lev", 30],["pair", ["ground_id", 4]],["reward", [6000, 500, 1]],["type", 0],["id", 122]]),
dict([["req", "stone"],["des", ["采集石英","木材和石材用户建筑升级，投石车等物品的建造","采集石英"]],["checknum", 300],["lev", 30],["pair", ["objid", 5]],["reward", [6200, 480, 1]],["type", 1],["id", 123]]),
dict([["req", "stone"],["des", ["采集大理石","木材和石材用户建筑升级，投石车等物品的建造","采集大理石"]],["checknum", 200],["lev", 30],["pair", ["objid", 4]],["reward", [4000, 320, 0]],["type", 1],["id", 124]])
];
